rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

language: ruby

cache: bundler

services:
  - mongodb
  - redis-server

install:
  - "bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}"
  - "cd cli && bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}"

script:
  - 'bundle exec rspec'
  - 'cd cli && bundle exec rspec'
